import { useState } from 'react';
import { Orbit, Radio, Disc, Binary, Cpu, UserCheck } from 'lucide-react';

const pipelineNodes = [
  {
    id: 'satellite',
    title: 'Satellite',
    icon: Orbit,
    tag: 'ORBIT',
    desc: 'On-orbit telemetry and science frames generated by spacecraft subsystems.',
  },
  {
    id: 'pass',
    title: 'Contact Pass',
    icon: Radio,
    tag: 'LINK',
    desc: 'Line-of-sight tracking window between satellite and ground antenna.',
  },
  {
    id: 'ground-station',
    title: 'Ground Station',
    icon: Disc,
    tag: 'RF RECEPTION',
    desc: 'Steerable dish antenna locks on carrier, downconverts, and demodulates.',
  },
  {
    id: 'data',
    title: 'Packet Stream',
    icon: Binary,
    tag: 'DECODING',
    desc: 'Frame synchronization, Reed-Solomon/LDPC error correction, and decryption.',
  },
  {
    id: 'vyuh',
    title: 'Vyuh MCS',
    icon: Cpu,
    tag: 'TELEMETRY',
    desc: 'XTCE parameter decommutation, limit checking, and automated monitoring.',
  },
  {
    id: 'operator',
    title: 'Flight Console',
    icon: UserCheck,
    tag: 'COMMAND GATE',
    desc: 'Single-console operations display with dual-operator authorization.',
  },
];

export default function DataJourney() {
  const [activeNode, setActiveNode] = useState(0);

  return (
    <section
      id="data-journey"
      className="relative py-20 sm:py-28 bg-[#050811] text-white border-t border-white/10 overflow-hidden"
    >
      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="max-w-3xl mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-[6px] bg-[#0E1626] border border-white/10 text-xs font-mono text-[#47B2E4] mb-3">
            <span className="w-1.5 h-1.5 rounded-full bg-[#47B2E4]" />
            <span>DATA LIFECYCLE</span>
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-medium tracking-tight text-white mb-4 font-sans">
            From Space to Ground: The Data Journey
          </h2>
          <p className="text-[16px] text-[#94A3B8] font-normal leading-relaxed">
            Deterministic data pipeline from on-orbit telemetry generation to ground demodulation and verified operator display.
          </p>
        </div>

        {/* ── Visual Transit Pipeline Infographic ── */}
        <div className="p-5 sm:p-7 rounded-[8px] bg-[#080C16] border border-white/15 shadow-[0_12px_40px_rgba(0,0,0,0.5)] mb-8">
          
          <div className="flex items-center justify-between pb-3 mb-5 border-b border-white/10 text-xs font-mono text-[#64748B]">
            <span className="text-white font-medium">END-TO-END TELEMETRY PIPELINE</span>
            <span>6-STAGE TRANSIT ARCHITECTURE</span>
          </div>

          {/* SVG Schematic (Clean, unified typography, no microscopic clutter) */}
          <div className="mb-6 p-3 sm:p-4 rounded-[6px] bg-[#050811] border border-white/10 overflow-hidden">
            <div className="overflow-x-auto pb-1 scrollbar-thin scrollbar-thumb-white/10">
              <div className="min-w-[720px] sm:min-w-0 w-full aspect-[22/6] min-h-[170px]">
                <svg className="w-full h-full font-sans" viewBox="0 0 1080 180" preserveAspectRatio="xMidYMid meet">
                  <defs>
                    <linearGradient id="djBeamGrad" x1="0%" y1="0%" x2="0%" y2="100%">
                      <stop offset="0%" stopColor="#47B2E4" stopOpacity="0.4" />
                      <stop offset="100%" stopColor="#47B2E4" stopOpacity="0.02" />
                    </linearGradient>
                    <linearGradient id="djActiveGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                      <stop offset="0%" stopColor="#0E1E38" stopOpacity="0.95" />
                      <stop offset="100%" stopColor="#091322" stopOpacity="0.95" />
                    </linearGradient>
                  </defs>

                  {/* Connecting Bus Line */}
                  <line x1="80" y1="90" x2="1000" y2="90" stroke="rgba(255,255,255,0.08)" strokeWidth="2" strokeDasharray="6 4" />
                  <line
                    x1="80"
                    y1="90"
                    x2={80 + activeNode * 184}
                    y2="90"
                    stroke="#47B2E4"
                    strokeWidth="2"
                    strokeDasharray="4 2"
                    className="transition-all duration-300"
                  />

                  {/* Stage 01: Satellite */}
                  <g onClick={() => setActiveNode(0)} className="cursor-pointer">
                    <rect
                      x="10" y="15" width="148" height="150" rx="6"
                      fill={activeNode === 0 ? 'url(#djActiveGrad)' : '#080C16'}
                      stroke={activeNode === 0 ? '#47B2E4' : 'rgba(255,255,255,0.12)'}
                      strokeWidth={activeNode === 0 ? '1.5' : '1'}
                      className="transition-all duration-200"
                    />
                    <rect x="68" y="55" width="32" height="22" rx="2" fill="#0E1626" stroke="#47B2E4" strokeWidth="1.5" />
                    <rect x="34" y="60" width="30" height="12" rx="1" fill="#0A1C30" stroke="#7CCCED" strokeWidth="1" />
                    <rect x="104" y="60" width="30" height="12" rx="1" fill="#0A1C30" stroke="#7CCCED" strokeWidth="1" />
                    <circle cx="84" cy="85" r="3" fill="#47B2E4" />
                    <polygon points="84,88 64,118 104,118" fill="url(#djBeamGrad)" />
                    <text x="84" y="38" fill={activeNode === 0 ? '#47B2E4' : '#94A3B8'} fontSize="11" fontWeight="600" textAnchor="middle">01 Satellite</text>
                    <text x="84" y="142" fill="#FFFFFF" fontSize="11" fontWeight="500" textAnchor="middle">Orbital Bus</text>
                  </g>

                  {/* Stage 02: Contact Pass */}
                  <g onClick={() => setActiveNode(1)} className="cursor-pointer">
                    <rect
                      x="194" y="15" width="148" height="150" rx="6"
                      fill={activeNode === 1 ? 'url(#djActiveGrad)' : '#080C16'}
                      stroke={activeNode === 1 ? '#47B2E4' : 'rgba(255,255,255,0.12)'}
                      strokeWidth={activeNode === 1 ? '1.5' : '1'}
                      className="transition-all duration-200"
                    />
                    <line x1="210" y1="90" x2="326" y2="90" stroke="rgba(255,255,255,0.15)" strokeWidth="1" />
                    <path d="M 216 90 Q 268 38 320 90" fill="none" stroke="#47B2E4" strokeWidth="1.5" strokeDasharray="3 2" />
                    <circle cx="268" cy="52" r="3.5" fill="#47B2E4" />
                    <text x="268" y="38" fill={activeNode === 1 ? '#47B2E4' : '#94A3B8'} fontSize="11" fontWeight="600" textAnchor="middle">02 Contact Pass</text>
                    <text x="268" y="142" fill="#FFFFFF" fontSize="11" fontWeight="500" textAnchor="middle">Line-of-Sight Arc</text>
                  </g>

                  {/* Stage 03: Ground Dish */}
                  <g onClick={() => setActiveNode(2)} className="cursor-pointer">
                    <rect
                      x="378" y="15" width="148" height="150" rx="6"
                      fill={activeNode === 2 ? 'url(#djActiveGrad)' : '#080C16'}
                      stroke={activeNode === 2 ? '#47B2E4' : 'rgba(255,255,255,0.12)'}
                      strokeWidth={activeNode === 2 ? '1.5' : '1'}
                      className="transition-all duration-200"
                    />
                    <path d="M 426 62 Q 452 82 478 62" fill="none" stroke="#47B2E4" strokeWidth="2" />
                    <line x1="452" y1="74" x2="452" y2="58" stroke="#7CCCED" strokeWidth="1.5" />
                    <circle cx="452" cy="58" r="2.5" fill="#7CCCED" />
                    <line x1="452" y1="74" x2="452" y2="95" stroke="rgba(255,255,255,0.3)" strokeWidth="2" />
                    <polygon points="438,102 466,102 458,95 446,95" fill="#0E1626" stroke="rgba(255,255,255,0.2)" strokeWidth="1" />
                    <text x="452" y="38" fill={activeNode === 2 ? '#47B2E4' : '#94A3B8'} fontSize="11" fontWeight="600" textAnchor="middle">03 Ground Station</text>
                    <text x="452" y="142" fill="#FFFFFF" fontSize="11" fontWeight="500" textAnchor="middle">Demodulation</text>
                  </g>

                  {/* Stage 04: Packet Stream */}
                  <g onClick={() => setActiveNode(3)} className="cursor-pointer">
                    <rect
                      x="562" y="15" width="148" height="150" rx="6"
                      fill={activeNode === 3 ? 'url(#djActiveGrad)' : '#080C16'}
                      stroke={activeNode === 3 ? '#47B2E4' : 'rgba(255,255,255,0.12)'}
                      strokeWidth={activeNode === 3 ? '1.5' : '1'}
                      className="transition-all duration-200"
                    />
                    <g transform="translate(578, 58)">
                      <rect x="0" y="0" width="34" height="18" rx="2" fill="#0E223D" stroke="#47B2E4" strokeWidth="1" />
                      <text x="17" y="13" fill="#47B2E4" fontSize="8" fontWeight="600" textAnchor="middle">SYNC</text>
                      <rect x="38" y="0" width="46" height="18" rx="2" fill="#0B192C" stroke="rgba(255,255,255,0.2)" strokeWidth="1" />
                      <text x="61" y="13" fill="#94A3B8" fontSize="8" textAnchor="middle">DATA</text>
                      <rect x="88" y="0" width="28" height="18" rx="2" fill="#091A2A" stroke="#34D399" strokeWidth="1" />
                      <text x="102" y="13" fill="#34D399" fontSize="8" fontWeight="600" textAnchor="middle">FEC</text>
                    </g>
                    <text x="636" y="38" fill={activeNode === 3 ? '#47B2E4' : '#94A3B8'} fontSize="11" fontWeight="600" textAnchor="middle">04 Packet Stream</text>
                    <text x="636" y="142" fill="#FFFFFF" fontSize="11" fontWeight="500" textAnchor="middle">Frame Decoder</text>
                  </g>

                  {/* Stage 05: Vyuh MCS */}
                  <g onClick={() => setActiveNode(4)} className="cursor-pointer">
                    <rect
                      x="746" y="15" width="148" height="150" rx="6"
                      fill={activeNode === 4 ? 'url(#djActiveGrad)' : '#080C16'}
                      stroke={activeNode === 4 ? '#47B2E4' : 'rgba(255,255,255,0.12)'}
                      strokeWidth={activeNode === 4 ? '1.5' : '1'}
                      className="transition-all duration-200"
                    />
                    <rect x="764" y="55" width="112" height="48" rx="3" fill="#050B16" stroke="rgba(71,178,228,0.3)" strokeWidth="1" />
                    <text x="772" y="73" fill="#47B2E4" fontSize="8" fontWeight="600">DECOMMUTATION</text>
                    <text x="772" y="87" fill="#34D399" fontSize="8" fontFamily="monospace">STATUS: NOMINAL</text>
                    <text x="820" y="38" fill={activeNode === 4 ? '#47B2E4' : '#94A3B8'} fontSize="11" fontWeight="600" textAnchor="middle">05 Vyuh MCS</text>
                    <text x="820" y="142" fill="#FFFFFF" fontSize="11" fontWeight="500" textAnchor="middle">Mission Control</text>
                  </g>

                  {/* Stage 06: Flight Operator */}
                  <g onClick={() => setActiveNode(5)} className="cursor-pointer">
                    <rect
                      x="930" y="15" width="140" height="150" rx="6"
                      fill={activeNode === 5 ? 'url(#djActiveGrad)' : '#080C16'}
                      stroke={activeNode === 5 ? '#47B2E4' : 'rgba(255,255,255,0.12)'}
                      strokeWidth={activeNode === 5 ? '1.5' : '1'}
                      className="transition-all duration-200"
                    />
                    <rect x="948" y="55" width="104" height="48" rx="3" fill="#080E1A" stroke="rgba(251,191,36,0.35)" strokeWidth="1" />
                    <text x="1000" y="73" fill="#FBBF24" fontSize="8" fontWeight="600" textAnchor="middle">DUAL-AUTH GATE</text>
                    <text x="1000" y="88" fill="#34D399" fontSize="8" fontWeight="600" textAnchor="middle">AUTHORIZED</text>
                    <text x="1000" y="38" fill={activeNode === 5 ? '#47B2E4' : '#94A3B8'} fontSize="11" fontWeight="600" textAnchor="middle">06 Flight Console</text>
                    <text x="1000" y="142" fill="#FFFFFF" fontSize="11" fontWeight="500" textAnchor="middle">Operator Gated</text>
                  </g>
                </svg>
              </div>
            </div>
          </div>

          {/* ── 6-Card Interactive Stage Selector with Concise Descriptions ── */}
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">
            {pipelineNodes.map((node, i) => {
              const Icon = node.icon;
              const isSelected = activeNode === i;
              return (
                <button
                  key={node.id}
                  onClick={() => setActiveNode(i)}
                  className={`
                    p-3.5 rounded-[6px] border text-left transition-all duration-150 flex flex-col justify-between
                    ${isSelected
                      ? 'bg-[#0E1626] border-[#47B2E4] shadow-[0_4px_16px_rgba(71,178,228,0.2)]'
                      : 'bg-[#0B1220] border-white/10 hover:border-white/20'
                    }
                  `}
                >
                  <div>
                    <div className="flex items-center justify-between mb-2">
                      <span className="text-xs font-mono text-[#64748B]">0{i + 1}</span>
                      <Icon className={`w-4 h-4 ${isSelected ? 'text-[#47B2E4]' : 'text-[#64748B]'}`} />
                    </div>
                    <div className="text-[13px] font-medium text-white mb-1">
                      {node.title}
                    </div>
                    <p className="text-[11px] text-[#94A3B8] leading-relaxed line-clamp-2">
                      {node.desc}
                    </p>
                  </div>
                </button>
              );
            })}
          </div>

        </div>

      </div>
    </section>
  );
}
